// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

// THIS FILE WAS AUTO-GENERATED BY ./wpilibNewCommands/generate_hids.py. DO NOT MODIFY

package frc2713.robot.oi;

import edu.wpi.first.wpilibj.event.EventLoop;
import edu.wpi.first.wpilibj2.command.CommandScheduler;
import edu.wpi.first.wpilibj2.command.button.CommandGenericHID;
import edu.wpi.first.wpilibj2.command.button.Trigger;

/**
 * A version of {@link Vader4Controller} with {@link Trigger} factories for command-based.
 *
 * @see Vader4Controller
 */
@SuppressWarnings("MethodName")
public class CommandVader4Controller extends CommandGenericHID {
  private final Vader4Controller m_hid;

  /**
   * Construct an instance of a controller.
   *
   * @param port The port index on the Driver Station that the controller is plugged into.
   */
  public CommandVader4Controller(int port) {
    super(port);
    m_hid = new Vader4Controller(port);
  }

  /**
   * Get the underlying GenericHID object.
   *
   * @return the wrapped GenericHID object
   */
  @Override
  public Vader4Controller getHID() {
    return m_hid;
  }

  /** Constructs a Trigger instance around the A button's digital signal. */
  public Trigger a() {
    return a(CommandScheduler.getInstance().getDefaultButtonLoop());
  }

  public Trigger a(EventLoop loop) {
    return button(Vader4Controller.Button.kA.value, loop);
  }

  /** Constructs a Trigger instance around the B button's digital signal. */
  public Trigger b() {
    return b(CommandScheduler.getInstance().getDefaultButtonLoop());
  }

  public Trigger b(EventLoop loop) {
    return button(Vader4Controller.Button.kB.value, loop);
  }

  /** Constructs a Trigger instance around the X button's digital signal. */
  public Trigger x() {
    return x(CommandScheduler.getInstance().getDefaultButtonLoop());
  }

  public Trigger x(EventLoop loop) {
    return button(Vader4Controller.Button.kX.value, loop);
  }

  /** Constructs a Trigger instance around the Y button's digital signal. */
  public Trigger y() {
    return y(CommandScheduler.getInstance().getDefaultButtonLoop());
  }

  public Trigger y(EventLoop loop) {
    return button(Vader4Controller.Button.kY.value, loop);
  }

  /** Constructs a Trigger instance around the C button's digital signal. */
  public Trigger c() {
    return c(CommandScheduler.getInstance().getDefaultButtonLoop());
  }

  public Trigger c(EventLoop loop) {
    return button(Vader4Controller.Button.kC.value, loop);
  }

  /** Constructs a Trigger instance around the Z button's digital signal. */
  public Trigger z() {
    return z(CommandScheduler.getInstance().getDefaultButtonLoop());
  }

  public Trigger z(EventLoop loop) {
    return button(Vader4Controller.Button.kZ.value, loop);
  }

  /** Constructs a Trigger instance around the M1 button's digital signal. */
  public Trigger m1() {
    return m1(CommandScheduler.getInstance().getDefaultButtonLoop());
  }

  public Trigger m1(EventLoop loop) {
    return button(Vader4Controller.Button.kM1.value, loop);
  }

  /** Constructs a Trigger instance around the M2 button's digital signal. */
  public Trigger m2() {
    return m2(CommandScheduler.getInstance().getDefaultButtonLoop());
  }

  public Trigger m2(EventLoop loop) {
    return button(Vader4Controller.Button.kM2.value, loop);
  }

  /** Constructs a Trigger instance around the M3 button's digital signal. */
  public Trigger m3() {
    return m3(CommandScheduler.getInstance().getDefaultButtonLoop());
  }

  public Trigger m3(EventLoop loop) {
    return button(Vader4Controller.Button.kM3.value, loop);
  }

  /** Constructs a Trigger instance around the M4 button's digital signal. */
  public Trigger m4() {
    return m4(CommandScheduler.getInstance().getDefaultButtonLoop());
  }

  public Trigger m4(EventLoop loop) {
    return button(Vader4Controller.Button.kM4.value, loop);
  }

  /** Constructs a Trigger instance around the left bumper button's digital signal. */
  public Trigger leftBumper() {
    return leftBumper(CommandScheduler.getInstance().getDefaultButtonLoop());
  }

  public Trigger leftBumper(EventLoop loop) {
    return button(Vader4Controller.Button.kLeftBumper.value, loop);
  }

  /** Constructs a Trigger instance around the right bumper button's digital signal. */
  public Trigger rightBumper() {
    return rightBumper(CommandScheduler.getInstance().getDefaultButtonLoop());
  }

  public Trigger rightBumper(EventLoop loop) {
    return button(Vader4Controller.Button.kRightBumper.value, loop);
  }

  /** Constructs a Trigger instance around the back button's digital signal. */
  public Trigger back() {
    return back(CommandScheduler.getInstance().getDefaultButtonLoop());
  }

  public Trigger back(EventLoop loop) {
    return button(Vader4Controller.Button.kBack.value, loop);
  }

  /** Constructs a Trigger instance around the start button's digital signal. */
  public Trigger start() {
    return start(CommandScheduler.getInstance().getDefaultButtonLoop());
  }

  public Trigger start(EventLoop loop) {
    return button(Vader4Controller.Button.kStart.value, loop);
  }

  /** Constructs a Trigger instance around the left stick button's digital signal. */
  public Trigger leftStick() {
    return leftStick(CommandScheduler.getInstance().getDefaultButtonLoop());
  }

  public Trigger leftStick(EventLoop loop) {
    return button(Vader4Controller.Button.kLeftStick.value, loop);
  }

  /** Constructs a Trigger instance around the right stick button's digital signal. */
  public Trigger rightStick() {
    return rightStick(CommandScheduler.getInstance().getDefaultButtonLoop());
  }

  public Trigger rightStick(EventLoop loop) {
    return button(Vader4Controller.Button.kRightStick.value, loop);
  }

  /** Constructs a Trigger instance around the axis value of the left trigger. */
  public Trigger leftTrigger(double threshold, EventLoop loop) {
    return axisGreaterThan(Vader4Controller.Axis.kLeftTrigger.value, threshold, loop);
  }

  public Trigger leftTrigger(double threshold) {
    return leftTrigger(threshold, CommandScheduler.getInstance().getDefaultButtonLoop());
  }

  public Trigger leftTrigger() {
    return leftTrigger(0.5);
  }

  /** Constructs a Trigger instance around the axis value of the right trigger. */
  public Trigger rightTrigger(double threshold, EventLoop loop) {
    return axisGreaterThan(Vader4Controller.Axis.kRightTrigger.value, threshold, loop);
  }

  public Trigger rightTrigger(double threshold) {
    return rightTrigger(threshold, CommandScheduler.getInstance().getDefaultButtonLoop());
  }

  public Trigger rightTrigger() {
    return rightTrigger(0.5);
  }

  /** Get the X axis value of left side of the controller. */
  public double getLeftX() {
    return m_hid.getLeftX();
  }

  /** Get the X axis value of right side of the controller. */
  public double getRightX() {
    return m_hid.getRightX();
  }

  /** Get the Y axis value of left side of the controller. */
  public double getLeftY() {
    return m_hid.getLeftY();
  }

  /** Get the Y axis value of right side of the controller. */
  public double getRightY() {
    return m_hid.getRightY();
  }

  /** Get the left trigger axis value of the controller. */
  public double getLeftTriggerAxis() {
    return m_hid.getLeftTriggerAxis();
  }

  /** Get the right trigger axis value of the controller. */
  public double getRightTriggerAxis() {
    return m_hid.getRightTriggerAxis();
  }
}
