// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

// THIS FILE WAS AUTO-GENERATED BY ./wpilibj/generate_hids.py. DO NOT MODIFY

package frc2713.robot.oi;

import edu.wpi.first.hal.FRCNetComm.tResourceType;
import edu.wpi.first.hal.HAL;
import edu.wpi.first.util.sendable.Sendable;
import edu.wpi.first.util.sendable.SendableBuilder;
import edu.wpi.first.wpilibj.GenericHID;
import edu.wpi.first.wpilibj.event.BooleanEvent;
import edu.wpi.first.wpilibj.event.EventLoop;

/**
 * Handle input from Vader4 controllers connected to the Driver Station.
 *
 * <p>This class handles Vader4 input that comes from the Driver Station. Each time a value is
 * requested the most recent value is returned. There is a single class instance for each controller
 * and the mapping of ports to hardware buttons depends on the code in the Driver Station.
 *
 * <p>Only first party controllers from Microsoft are guaranteed to have the correct mapping, and
 * only through the official NI DS. Sim is not guaranteed to have the same mapping, as well as any
 * 3rd party controllers.
 */
public class Vader4Controller extends GenericHID implements Sendable {
  /** Represents a digital button on a Vader4Controller. */
  public enum Button {
    /** A button. */
    kA(1),
    /** B button. */
    kB(2),
    /** X button. */
    kX(4),
    /** Y button. */
    kY(5),
    /** Left bumper button. */
    kLeftBumper(5),
    /** Right bumper button. */
    kRightBumper(6),
    /** Back button. */
    kBack(7),
    /** Start button. */
    kStart(8),
    /** Left stick button. */
    kLeftStick(13),
    /** Right stick button. */
    kRightStick(14),
    /** C button */
    kC(3),
    /** Z button */
    kZ(6),
    /** M1 Button */
    kM1(15),
    /** M2 Button */
    kM2(16),
    /** M3 Button */
    kM3(17),
    /** M4 Button */
    kM4(18);

    /** Button value. */
    public final int value;

    Button(int value) {
      this.value = value;
    }

    /**
     * Get the human-friendly name of the button, matching the relevant methods. This is done by
     * stripping the leading `k`, and appending `Button`.
     *
     * <p>Primarily used for automated unit tests.
     *
     * @return the human-friendly name of the button.
     */
    @Override
    public String toString() {
      // Remove leading `k`
      return this.name().substring(1) + "Button";
    }
  }

  /** Represents an axis on a Vader4Controller. */
  public enum Axis {
    /** Left X axis. */
    kLeftX(0),
    /** Right X axis. */
    kRightX(2),
    /** Left Y axis. */
    kLeftY(1),
    /** Right Y axis. */
    kRightY(3),
    /** Left trigger. */
    kLeftTrigger(5),
    /** Right trigger. */
    kRightTrigger(4);

    /** Axis value. */
    public final int value;

    Axis(int value) {
      this.value = value;
    }

    /**
     * Get the human-friendly name of the axis, matching the relevant methods. This is done by
     * stripping the leading `k`, and appending `Axis` if the name ends with `Trigger`.
     *
     * <p>Primarily used for automated unit tests.
     *
     * @return the human-friendly name of the axis.
     */
    @Override
    public String toString() {
      var name = this.name().substring(1); // Remove leading `k`
      if (name.endsWith("Trigger")) {
        return name + "Axis";
      }
      return name;
    }
  }

  /**
   * Construct an instance of a controller.
   *
   * @param port The port index on the Driver Station that the controller is plugged into (0-5).
   */
  public Vader4Controller(final int port) {
    super(port);
    HAL.report(tResourceType.kResourceType_XboxController, port + 1);
  }

  /**
   * Get the X axis value of left side of the controller. Right is positive.
   *
   * @return The axis value.
   */
  public double getLeftX() {
    return getRawAxis(Axis.kLeftX.value);
  }

  /**
   * Get the X axis value of right side of the controller. Right is positive.
   *
   * @return The axis value.
   */
  public double getRightX() {
    return getRawAxis(Axis.kRightX.value);
  }

  /**
   * Get the Y axis value of left side of the controller. Back is positive.
   *
   * @return The axis value.
   */
  public double getLeftY() {
    return getRawAxis(Axis.kLeftY.value);
  }

  /**
   * Get the Y axis value of right side of the controller. Back is positive.
   *
   * @return The axis value.
   */
  public double getRightY() {
    return getRawAxis(Axis.kRightY.value);
  }

  /**
   * Get the left trigger axis value of the controller. Note that this axis is bound to the range of
   * [0, 1] as opposed to the usual [-1, 1].
   *
   * @return The axis value.
   */
  public double getLeftTriggerAxis() {
    return getRawAxis(Axis.kLeftTrigger.value);
  }

  /**
   * Constructs an event instance around the axis value of the left trigger. The returned trigger
   * will be true when the axis value is greater than {@code threshold}.
   *
   * @param threshold the minimum axis value for the returned {@link BooleanEvent} to be true. This
   *     value should be in the range [0, 1] where 0 is the unpressed state of the axis.
   * @param loop the event loop instance to attach the event to.
   * @return an event instance that is true when the left trigger's axis exceeds the provided
   *     threshold, attached to the given event loop
   */
  public BooleanEvent leftTrigger(double threshold, EventLoop loop) {
    return axisGreaterThan(Axis.kLeftTrigger.value, threshold, loop);
  }

  /**
   * Constructs an event instance around the axis value of the left trigger. The returned trigger
   * will be true when the axis value is greater than 0.5.
   *
   * @param loop the event loop instance to attach the event to.
   * @return an event instance that is true when the left trigger's axis exceeds the provided
   *     threshold, attached to the given event loop
   */
  public BooleanEvent leftTrigger(EventLoop loop) {
    return leftTrigger(0.5, loop);
  }

  /**
   * Get the right trigger axis value of the controller. Note that this axis is bound to the range
   * of [0, 1] as opposed to the usual [-1, 1].
   *
   * @return The axis value.
   */
  public double getRightTriggerAxis() {
    return getRawAxis(Axis.kRightTrigger.value);
  }

  /**
   * Constructs an event instance around the axis value of the right trigger. The returned trigger
   * will be true when the axis value is greater than {@code threshold}.
   *
   * @param threshold the minimum axis value for the returned {@link BooleanEvent} to be true. This
   *     value should be in the range [0, 1] where 0 is the unpressed state of the axis.
   * @param loop the event loop instance to attach the event to.
   * @return an event instance that is true when the right trigger's axis exceeds the provided
   *     threshold, attached to the given event loop
   */
  public BooleanEvent rightTrigger(double threshold, EventLoop loop) {
    return axisGreaterThan(Axis.kRightTrigger.value, threshold, loop);
  }

  /**
   * Constructs an event instance around the axis value of the right trigger. The returned trigger
   * will be true when the axis value is greater than 0.5.
   *
   * @param loop the event loop instance to attach the event to.
   * @return an event instance that is true when the right trigger's axis exceeds the provided
   *     threshold, attached to the given event loop
   */
  public BooleanEvent rightTrigger(EventLoop loop) {
    return rightTrigger(0.5, loop);
  }

  // Button methods for A, B, X, Y, C, Z, M1-M4, bumpers, back, start, and sticks
  // (continuing with full implementation...)

  /** Read the value of the A button. */
  public boolean getAButton() {
    return getRawButton(Button.kA.value);
  }

  public boolean getAButtonPressed() {
    return getRawButtonPressed(Button.kA.value);
  }

  public boolean getAButtonReleased() {
    return getRawButtonReleased(Button.kA.value);
  }

  public BooleanEvent a(EventLoop loop) {
    return button(Button.kA.value, loop);
  }

  /** Read the value of the B button. */
  public boolean getBButton() {
    return getRawButton(Button.kB.value);
  }

  public boolean getBButtonPressed() {
    return getRawButtonPressed(Button.kB.value);
  }

  public boolean getBButtonReleased() {
    return getRawButtonReleased(Button.kB.value);
  }

  public BooleanEvent b(EventLoop loop) {
    return button(Button.kB.value, loop);
  }

  /** Read the value of the X button. */
  public boolean getXButton() {
    return getRawButton(Button.kX.value);
  }

  public boolean getXButtonPressed() {
    return getRawButtonPressed(Button.kX.value);
  }

  public boolean getXButtonReleased() {
    return getRawButtonReleased(Button.kX.value);
  }

  public BooleanEvent x(EventLoop loop) {
    return button(Button.kX.value, loop);
  }

  /** Read the value of the Y button. */
  public boolean getYButton() {
    return getRawButton(Button.kY.value);
  }

  public boolean getYButtonPressed() {
    return getRawButtonPressed(Button.kY.value);
  }

  public boolean getYButtonReleased() {
    return getRawButtonReleased(Button.kY.value);
  }

  public BooleanEvent y(EventLoop loop) {
    return button(Button.kY.value, loop);
  }

  /** Read the value of the C button. */
  public boolean getCButton() {
    return getRawButton(Button.kC.value);
  }

  public boolean getCButtonPressed() {
    return getRawButtonPressed(Button.kC.value);
  }

  public boolean getCButtonReleased() {
    return getRawButtonReleased(Button.kC.value);
  }

  public BooleanEvent c(EventLoop loop) {
    return button(Button.kC.value, loop);
  }

  /** Read the value of the Z button. */
  public boolean getZButton() {
    return getRawButton(Button.kZ.value);
  }

  public boolean getZButtonPressed() {
    return getRawButtonPressed(Button.kZ.value);
  }

  public boolean getZButtonReleased() {
    return getRawButtonReleased(Button.kZ.value);
  }

  public BooleanEvent z(EventLoop loop) {
    return button(Button.kZ.value, loop);
  }

  /** Read the value of the M1 button. */
  public boolean getM1Button() {
    return getRawButton(Button.kM1.value);
  }

  public boolean getM1ButtonPressed() {
    return getRawButtonPressed(Button.kM1.value);
  }

  public boolean getM1ButtonReleased() {
    return getRawButtonReleased(Button.kM1.value);
  }

  public BooleanEvent m1(EventLoop loop) {
    return button(Button.kM1.value, loop);
  }

  /** Read the value of the M2 button. */
  public boolean getM2Button() {
    return getRawButton(Button.kM2.value);
  }

  public boolean getM2ButtonPressed() {
    return getRawButtonPressed(Button.kM2.value);
  }

  public boolean getM2ButtonReleased() {
    return getRawButtonReleased(Button.kM2.value);
  }

  public BooleanEvent m2(EventLoop loop) {
    return button(Button.kM2.value, loop);
  }

  /** Read the value of the M3 button. */
  public boolean getM3Button() {
    return getRawButton(Button.kM3.value);
  }

  public boolean getM3ButtonPressed() {
    return getRawButtonPressed(Button.kM3.value);
  }

  public boolean getM3ButtonReleased() {
    return getRawButtonReleased(Button.kM3.value);
  }

  public BooleanEvent m3(EventLoop loop) {
    return button(Button.kM3.value, loop);
  }

  /** Read the value of the M4 button. */
  public boolean getM4Button() {
    return getRawButton(Button.kM4.value);
  }

  public boolean getM4ButtonPressed() {
    return getRawButtonPressed(Button.kM4.value);
  }

  public boolean getM4ButtonReleased() {
    return getRawButtonReleased(Button.kM4.value);
  }

  public BooleanEvent m4(EventLoop loop) {
    return button(Button.kM4.value, loop);
  }

  /** Read the value of the left bumper button. */
  public boolean getLeftBumperButton() {
    return getRawButton(Button.kLeftBumper.value);
  }

  public boolean getLeftBumperButtonPressed() {
    return getRawButtonPressed(Button.kLeftBumper.value);
  }

  public boolean getLeftBumperButtonReleased() {
    return getRawButtonReleased(Button.kLeftBumper.value);
  }

  public BooleanEvent leftBumper(EventLoop loop) {
    return button(Button.kLeftBumper.value, loop);
  }

  /** Read the value of the right bumper button. */
  public boolean getRightBumperButton() {
    return getRawButton(Button.kRightBumper.value);
  }

  public boolean getRightBumperButtonPressed() {
    return getRawButtonPressed(Button.kRightBumper.value);
  }

  public boolean getRightBumperButtonReleased() {
    return getRawButtonReleased(Button.kRightBumper.value);
  }

  public BooleanEvent rightBumper(EventLoop loop) {
    return button(Button.kRightBumper.value, loop);
  }

  /** Read the value of the back button. */
  public boolean getBackButton() {
    return getRawButton(Button.kBack.value);
  }

  public boolean getBackButtonPressed() {
    return getRawButtonPressed(Button.kBack.value);
  }

  public boolean getBackButtonReleased() {
    return getRawButtonReleased(Button.kBack.value);
  }

  public BooleanEvent back(EventLoop loop) {
    return button(Button.kBack.value, loop);
  }

  /** Read the value of the start button. */
  public boolean getStartButton() {
    return getRawButton(Button.kStart.value);
  }

  public boolean getStartButtonPressed() {
    return getRawButtonPressed(Button.kStart.value);
  }

  public boolean getStartButtonReleased() {
    return getRawButtonReleased(Button.kStart.value);
  }

  public BooleanEvent start(EventLoop loop) {
    return button(Button.kStart.value, loop);
  }

  /** Read the value of the left stick button. */
  public boolean getLeftStickButton() {
    return getRawButton(Button.kLeftStick.value);
  }

  public boolean getLeftStickButtonPressed() {
    return getRawButtonPressed(Button.kLeftStick.value);
  }

  public boolean getLeftStickButtonReleased() {
    return getRawButtonReleased(Button.kLeftStick.value);
  }

  public BooleanEvent leftStick(EventLoop loop) {
    return button(Button.kLeftStick.value, loop);
  }

  /** Read the value of the right stick button. */
  public boolean getRightStickButton() {
    return getRawButton(Button.kRightStick.value);
  }

  public boolean getRightStickButtonPressed() {
    return getRawButtonPressed(Button.kRightStick.value);
  }

  public boolean getRightStickButtonReleased() {
    return getRawButtonReleased(Button.kRightStick.value);
  }

  public BooleanEvent rightStick(EventLoop loop) {
    return button(Button.kRightStick.value, loop);
  }

  @Override
  public void initSendable(SendableBuilder builder) {
    builder.setSmartDashboardType("HID");
    builder.publishConstString("ControllerType", "Xbox");
    builder.addDoubleProperty("LeftTrigger", this::getLeftTriggerAxis, null);
    builder.addDoubleProperty("RightTrigger", this::getRightTriggerAxis, null);
    builder.addDoubleProperty("LeftX", this::getLeftX, null);
    builder.addDoubleProperty("RightX", this::getRightX, null);
    builder.addDoubleProperty("LeftY", this::getLeftY, null);
    builder.addDoubleProperty("RightY", this::getRightY, null);
    builder.addBooleanProperty("A", this::getAButton, null);
    builder.addBooleanProperty("B", this::getBButton, null);
    builder.addBooleanProperty("X", this::getXButton, null);
    builder.addBooleanProperty("Y", this::getYButton, null);
    builder.addBooleanProperty("LeftBumper", this::getLeftBumperButton, null);
    builder.addBooleanProperty("RightBumper", this::getRightBumperButton, null);
    builder.addBooleanProperty("Back", this::getBackButton, null);
    builder.addBooleanProperty("Start", this::getStartButton, null);
    builder.addBooleanProperty("LeftStick", this::getLeftStickButton, null);
    builder.addBooleanProperty("RightStick", this::getRightStickButton, null);
    builder.addBooleanProperty("C", this::getCButton, null);
    builder.addBooleanProperty("Z", this::getZButton, null);
    builder.addBooleanProperty("M1", this::getM1Button, null);
    builder.addBooleanProperty("M2", this::getM2Button, null);
    builder.addBooleanProperty("M3", this::getM3Button, null);
    builder.addBooleanProperty("M4", this::getM4Button, null);
  }
}
